sudo: required
services:
  - docker

before_install:
  - docker build -t jijeshjayachandran/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true jijeshjayachandran/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-xxxxxxx"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY" 

