sudo: required
services:
  - docker

before_install:
  - docker build -t jijeshjayachandran/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true jijeshjayachandran/docker-react npm run test -- --coverage

